# Run docker-compose build
# Run docker-compose up

version: '3.1'

services:

  foglamp:
    container_name: foglamp-gui
    image: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
      # - "443:443"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
